import Head from "next/head";
import { Box, Button, Container, SimpleGrid } from "@chakra-ui/react";
import { GetServerSideProps } from "next";
import { Recipe } from "../common/Recipe";
import { api } from "../services/api";
import { RecipeCard } from "../components/RecipeCard";
import { parseCookies } from "nookies";

export const getServerSideProps: GetServerSideProps<{
  recipes: Recipe[];
}> = async (ctx) => {
  const getSavedIngredients = parseCookies(ctx)["@ReceitaCheck:ingredients"];

  let alreadyOwnsIngredients = [];

  if (getSavedIngredients) {
    alreadyOwnsIngredients = JSON.parse(getSavedIngredients).map(
      (ingredient) => ingredient.id
    );
  }

  const res = await api.post("recipes/list", {
    ingredients: alreadyOwnsIngredients,
  });

  return { props: { recipes: res.data } };
};

export default function Home({ recipes }: { recipes: Recipe[] }) {
  return (
    <>
      <Head>
        <title>Receita Check - Receitas com o que você tem</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Container my={8} w="full" maxW="1280px">
        <SimpleGrid spacing={8} columns={3}>
          {recipes.map((recipe) => (
            <RecipeCard recipe={recipe} key={recipe.id} />
          ))}
        </SimpleGrid>
      </Container>
    </>
  );
}
